# Redirect HTTP to HTTPS
server {
    listen 80;
    server_name forestvision.site www.forestvision.site;

    return 301 https://$host$request_uri;
}

# HTTPS Server
server {
    listen 443 ssl;
    server_name forestvision.site www.forestvision.site;

    ssl_certificate /etc/letsencrypt/live/forestvision.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/forestvision.site/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    
    # Block hidden files (.env, .git, etc.)
    location ~ /\. {
        deny all;
        return 404;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Backend API
    location /api/ {
        proxy_pass http://backend:5000/api/;
        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;

        proxy_cache_bypass $http_upgrade;
    }
}
