const mongoose = require('mongoose');
const Data = require('../models/Data');
const pipelineService = require('../services/pipelineService');
const dotenv = require('dotenv');
const path = require('path');

// Load env vars
dotenv.config({ path: path.resolve(__dirname, '../.env') });

const regionsToSeed = [
    "Pakistan",
    "Khyber Pakhtunkhwa (KP)",
    "Galyat & Hazara Forest Belt",
    "Abbottabad",
    "Jinnahabad",
    "Mandian",
    "Supply Bazaar",
    "Kehal",
    "Malikpura",
    "Nawanshehr",
    "PMA / Kakul Area",
    "Bilal Town",
    "Peshawar",
    "University Town",
    "Hayatabad (Phases 1–7)",
    "Saddar",
    "Gulbahar",
    "Kohat Road",
    "Ring Road Area",
    "Tehkal",
    "Dabgari",
    "Hashtnagri",
    "Board Bazaar",
    "Mardan",
    "Sheikh Maltoon Town",
    "Baghdada",
    "Par Hoti",
    "Bijli Ghar",
    "College Chowk Area",
    "Nowshera Road Area",
    "Kohat",
    "Kohat Cantonment",
    "Jarma",
    "Ustarzai",
    "KDA Township",
    "Togh Bala",
    "Nathia Gali",
    "Dunga Gali",
    "Khanspur",
    "Thandiani",
    "Ghora Dhaka",
    "Ayubia",
    "Sherwan",
    "Makhniyal",
    "Balakot",
    "Balakot Bazaar",
    "Garlat",
    "Sangar",
    "Satbani",
    "Nadi Kinara Area",
    "Mahandri",
    "Paras",
    "Shinu",
    "Jared",
    "Naran",
    "Main Bazaar",
    "Saif-ul-Malook Road",
    "Batakundi",
    "Jalkhad",
    "Shinkiari (Siran forest belt)",
    "Swat–Malakand Forest Belt",
    "Mingora",
    "Saidu Sharif",
    "Gulkada",
    "Shahdara",
    "Rahimabad",
    "Amankot",
    "Kanju Township",
    "Kanju",
    "Odigram",
    "Landikas",
    "Airport Road Area",
    "Swat",
    "Kalam",
    "Ushu",
    "Bahrain",
    "Madyan",
    "Dir–Chitral–Buner–Shangla Forests",
    "Dir",
    "Dir Bazaar",
    "Barawal",
    "Ashiri Dara",
    "Rabat",
    "Chitral",
    "Chitral Town",
    "Ayun",
    "Drosh",
    "Reshun",
    "Danin",
    "Daggar (Buner)",
    "Alpuri (Shangla)",
    "Kohistan & Indus Valley Forests",
    "Dassu",
    "Komila",
    "Seo",
    "Kandia",
    "Jalkot",
    "Pattan",
    "Besham",
    "Palas Valley settlements",
    "Islamabad Capital Territory & Margalla Region",
    "Islamabad",
    "F-6",
    "F-7",
    "F-8",
    "F-10",
    "F-11",
    "G-6",
    "G-7",
    "G-8",
    "G-9",
    "G-10",
    "G-11",
    "I-8",
    "I-9",
    "I-10",
    "E-7 (Diplomatic area)",
    "Bahria Town (nearby)",
    "DHA Islamabad",
    "Bhara Kahu",
    "Shah Allah Ditta",
    "Bani Gala",
    "Saidpur",
    "Gokina",
    "Trail-side settlements (Trails 3, 5, 6 belt)",
    "Punjab",
    "Hill & Subtropical Forest Towns",
    "Murree",
    "Kotli Sattian",
    "Kallar Syedan (upper belt)",
    "Khabeki",
    "Naushera",
    "Plantation & Reserved Forest Towns",
    "Lahore",
    "Gulberg",
    "DHA (Phases 1–9)",
    "Johar Town",
    "Model Town",
    "Township",
    "Cantt",
    "Wapda Town",
    "Bahria Town",
    "Valencia",
    "Allama Iqbal Town",
    "Faisalabad",
    "Peoples Colony",
    "Madina Town",
    "Jinnah Colony",
    "Gulistan Colony",
    "D-Type Colony",
    "Canal Road Area",
    "Susan Road",
    "Rawalpindi",
    "Satellite Town",
    "Chaklala",
    "DHA",
    "Raja Bazaar",
    "Adiala Road",
    "Peshawar Road Area",
    "Multan",
    "Gulgasht Colony",
    "Bosan Road",
    "Shah Rukn-e-Alam",
    "Mumtazabad",
    "New Multan",
    "Gujranwala",
    "DC Colony",
    "Sialkot",
    "Paris Road",
    "Hajipura",
    "Shahabpura",
    "Defence Road Area",
    "Bahawalpur",
    "Model Town A/B/C",
    "Yazman Road Area",
    "Dubai Mahal Road",
    "Sargodha",
    "University Road Area",
    "Farooq Colony",
    "Chichawatni",
    "Changa Manga",
    "Gatwala (near Faisalabad)",
    "Rakh Jhok (Sheikhupura)",
    "Pirowal (near Khanewal)",
    "Daphar / Pindi Bhattian",
    "Mandi Bahauddin / Phalia (Mona–Daphar)",
    "Shorkot",
    "Kundian",
    "Riverine Forest Belt (Indus)",
    "Dera Ghazi Khan",
    "Block 15/16",
    "College Road",
    "Sakhi Sarwar Road",
    "Taunsa Sharif",
    "Layyah",
    "Muzaffargarh",
    "Alipur Road Area",
    "Khangarh Road",
    "City Housing Colony",
    "Kot Addu",
    "Cantt Area",
    "Chowk Sarwar Shaheed Road",
    "KAPCO Colony",
    "Sindh",
    "Indus Riverine Forest Towns",
    "Sukkur",
    "New Pind",
    "Military Road",
    "Shikarpur Road Area",
    "Rohri Link Area",
    "Rohri",
    "Shikarpur",
    "Ghotki",
    "Kandhkot",
    "Kashmore",
    "Sehwan",
    "Dadu",
    "Mangrove & Coastal Forest Settlements",
    "Keti Bunder",
    "Shah Bunder",
    "Kharo Chan",
    "Jati",
    "Mirpur Sakro",
    "Ghorabari",
    "Other Forest-Associated Towns",
    "Sanghar / Sinjhoro (Makhi Forest area)",
    "Badin (Hadero Lake forests)",
    "Karachi (Clifton Urban Forest zone)",
    "Hyderabad",
    "Latifabad (Units 1–12)",
    "Qasimabad",
    "Autobhan Road",
    "Citizen Colony",
    "Larkana",
    "Ratodero Road",
    "Sachal Colony",
    "VIP Road",
    "Naudero Road",
    "Mirpur Khas",
    "Sindhri Road",
    "Hirabad",
    "Model Colony",
    "Balochistan",
    "Juniper & Dry Forest Towns",
    "Ziarat",
    "Ziarat Town",
    "Prospect Point Area",
    "Sanjavi Road",
    "Quetta",
    "Jinnah Town",
    "Samungli Road",
    "Brewery Road",
    "Zarghoon Road",
    "Kalat",
    "Khuzdar",
    "Gwadar",
    "New Town",
    "Old Town",
    "Gwadar Port Area",
    "Marine Drive",
    "Turbat",
    "Absar",
    "Loralai",
    "Harnai",
    "Barkhan",
    "Musakhel",
    "Zarghoon / Hanna (near Quetta)",
    "Harboi (near Kalat)",
    "Takatu Mountain settlements",
    "Suleiman Range foothill settlements",
    "Gilgit-Baltistan (GB)",
    "Alpine & Valley Forest Towns",
    "Gilgit",
    "Konodas",
    "Jutial",
    "Kashrote",
    "Danyore",
    "Baseen",
    "Skardu",
    "Hussainabad",
    "Khaplu Road Area",
    "Sadpara",
    "Kharpocho Area",
    "Astore",
    "Rama Meadows settlements",
    "Hunza",
    "Karimabad",
    "Aliabad",
    "Gulmit",
    "Passu",
    "Nagar",
    "Gahkuch (Ghizer)",
    "Phander",
    "Yasin",
    "Bagrot Valley settlements",
    "Naltar Bala",
    "Azad Jammu & Kashmir (AJK)",
    "Major Forest-Dominant Towns",
    "Muzaffarabad",
    "Chattar",
    "Upper Adda",
    "Lower Plate",
    "Sathra",
    "Rawalakot",
    "Thorar",
    "Banjosa Road",
    "Bagh",
    "Chela Bandi",
    "Dhirkot Road",
    "Kotli",
    "Bhimber",
    "Valley & High-Forest Settlements",
    "Neelum Valley towns",
    "Keran",
    "Sharda",
    "Leepa / Reshian",
    "Forward Kahuta (Haveli)",
    "Mong (Sudhnoti)",
    "Pir Chinasi region",
    "Tolipir region"
];

const seedData = async () => {
    try {
        console.log('🔌 Connecting to MongoDB...');
        await mongoose.connect(process.env.MONGODB_URI);
        console.log('✅ Connected to MongoDB');

        for (const region of regionsToSeed) {
            console.log(`\n🌊 Fetching data for: ${region}...`);
            const startDate = '2023-01-01';
            const endDate = '2023-12-31';

            try {
                // 1. Run Pipeline
                const pipelineResult = await pipelineService.runDataPipeline(region, startDate, endDate);

                if (!pipelineResult) {
                    console.error(`❌ No result returned for ${region}`);
                    continue;
                }

                // 2. Save to MongoDB
                const newDataset = new Data({
                    region,
                    timeRange: { start: new Date(startDate), end: new Date(endDate) },
                    sourceApi: 'Unified Python Pipeline (Seeded)',
                    rawData: pipelineResult,
                    metadata: {
                        executedAt: new Date(),
                        pipelineStatus: pipelineResult.status || 'success'
                    }
                });

                await newDataset.save();
                console.log(`✅ stored data for ${region}`);

            } catch (err) {
                console.error(`❌ Failed to process ${region}:`, err.message);
                if (err.message.includes('code 1')) {
                    console.error("   (Check if Python script dependencies are installed or if 'regions.py' has the region)");
                }
            }
        }

        console.log('\n🎉 Seeding Complete.');
        process.exit(0);

    } catch (error) {
        console.error('❌ Fatal Error:', error.message);
        process.exit(1);
    }
};

seedData();
